name: GiveAllPlayers
version: '${project.version}'
main: me.atomictempest.giveallplayers.GiveAllPlayers
api-version: 1.18
authors: [ AtomicTempest ]
description: Plugin to give all players an item
commands:
  giveall:
    description: give items to player you choose online
    usage: /<command>
  giveallplayers:
    description: give items to currently all online players
    usage: /<command>